name: Run Unit Tests on Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run test command
        run: yarn test
